version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: pizza
      MYSQL_DATABASE: pizza
      MYSQL_USER: root
      MYSQL_PASSWORD: pizza
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql